### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by davezrave** [nathancarnes/MultiDomain#1]
Hi Nathan

Sorry for the post in the issues section, just have a question about this working on a Multisite setup.

I had this working perfectly on a stand alone site but I was wondering if there is any way of this working on a root site within Multisite?

Thank you

Dave

**Comment by nathancarnes** [comment]
Hi Dave,

Right now there aren't any plans to support Multisite. I can see the use case, but for now it's lower priority than things like moving config to the database and an admin interface.

That said, if there are a lot of requests for it I'll re-prioritize, or I'll of course happily accept pull requests ;)

Cheers,

Nathan
