### ISSUE TITLE
Recursive redirection

### ISSUE THREAD

**Issue by JulianTosh** [nathancarnes/MultiDomain#2]
I am having trouble with page traversal on multi'd domains.

My main/top domain "AVInternet.com" works as expected. It is not listed in the config.php file as a domain.

My other URLs in domains listed in the config.php, however, are becoming recursive and 404ing after two clicks. For example:

Visit: http://bit-remit.com/
Then click on a menu like "Partner Domains" and you get: http://bit-remit.com/Bit-Remit.com/partner-domains/

Then click back on "home" and you get: http://bit-remit.com/Bit-Remit.com/partner-domains/Bit-Remit.com/

If you click on "Blog" at that point, the browser says it's not redirecting properly and white screens.

**Comment by nathancarnes** [comment]
Can you paste in your config.php so I can take a look?

**Comment by JulianTosh** [comment]
<?php
$domains = array(
  array(
    'domain' => 'bit-remit.com',
    'siteurl' => 'Bit-Remit.com',
    'home' => 'Bit-Remit.com',
    'blogname' => 'Bit-Remit.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoinarchive.com',
    'siteurl' => 'BitcoinArchive.com',
    'home' => 'BitcoinArchive.com',
    'blogname' => 'BitcoinArchive.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoincyberstore.com',
    'siteurl' => 'BitcoinCyberStore.com',
    'home' => 'BitcoinCyberStore.com',
    'blogname' => 'BitcoinCyberStore.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoinfortress.com',
    'siteurl' => 'BitcoinFortress.com',
    'home' => 'BitcoinFortress.com',
    'blogname' => 'BitcoinFortress.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoinintro.com',
    'siteurl' => 'BitcoinIntro.com',
    'home' => 'BitcoinIntro.com',
    'blogname' => 'BitcoinIntro.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoinoffline.com',
    'siteurl' => 'BitcoinOffline.com',
    'home' => 'BitcoinOffline.com',
    'blogname' => 'BitcoinOffline.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoinsanctuary.com',
    'siteurl' => 'BitcoinSanctuary.com',
    'home' => 'BitcoinSanctuary.com',
    'blogname' => 'BitcoinSanctuary.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoinshopper.com',
    'siteurl' => 'BitcoinShopper.com',
    'home' => 'BitcoinShopper.com',
    'blogname' => 'BitcoinShopper.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitcoinweekly.info',
    'siteurl' => 'BitcoinWeekly.info',
    'home' => 'BitcoinWeekly.info',
    'blogname' => 'BitcoinWeekly.info',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'bitlister.com',
    'siteurl' => 'BitLister.com',
    'home' => 'BitLister.com',
    'blogname' => 'BitLister.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'btcbus.com',
    'siteurl' => 'BTCBus.com',
    'home' => 'BTCBus.com',
    'blogname' => 'BTCBus.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'coin4.me',
    'siteurl' => 'Coin4.me',
    'home' => 'Coin4.me',
    'blogname' => 'Coin4.me',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'coinbus.com',
    'siteurl' => 'CoinBus.com',
    'home' => 'CoinBus.com',
    'blogname' => 'CoinBus.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'couldbeher.com',
    'siteurl' => 'CouldBeHer.com',
    'home' => 'CouldBeHer.com',
    'blogname' => 'CouldBeHer.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'couldbehim.com',
    'siteurl' => 'CouldBeHim.com',
    'home' => 'CouldBeHim.com',
    'blogname' => 'CouldBeHim.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'internettuffgirl.com',
    'siteurl' => 'InternetTuffGirl.com',
    'home' => 'InternetTuffGirl.com',
    'blogname' => 'InternetTuffGirl.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'offshorebitcoin.com',
    'siteurl' => 'OffshoreBitcoin.com',
    'home' => 'OffshoreBitcoin.com',
    'blogname' => 'OffshoreBitcoin.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'remitbit.com',
    'siteurl' => 'RemitBit.com',
    'home' => 'RemitBit.com',
    'blogname' => 'RemitBit.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'remitbitcoin.com',
    'siteurl' => 'RemitBitcoin.com',
    'home' => 'RemitBitcoin.com',
    'blogname' => 'RemitBitcoin.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'securemybitcoin.com',
    'siteurl' => 'SecureMyBitcoin.com',
    'home' => 'SecureMyBitcoin.com',
    'blogname' => 'SecureMyBitcoin.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'shopwithbitcoins.com',
    'siteurl' => 'ShopWithBitcoins.com',
    'home' => 'ShopWithBitcoins.com',
    'blogname' => 'ShopWithBitcoins.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'spesieze.com',
    'siteurl' => 'Spesieze.com',
    'home' => 'Spesieze.com',
    'blogname' => 'Spesieze.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'stripcoin.com',
    'siteurl' => 'StripCoin.com',
    'home' => 'StripCoin.com',
    'blogname' => 'StripCoin.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'thesecretsafe.com',
    'siteurl' => 'TheSecretSafe.com',
    'home' => 'TheSecretSafe.com',
    'blogname' => 'TheSecretSafe.com',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'tipover.net',
    'siteurl' => 'TipOver.net',
    'home' => 'TipOver.net',
    'blogname' => 'TipOver.net',
    'blogdescription' => 'Domain For Sale'
  ),
  array(
    'domain' => 'vegasbikers.com',
    'siteurl' => 'VegasBikers.com',
    'home' => 'VegasBikers.com',
    'blogname' => 'VegasBikers.com',
    'blogdescription' => 'Domain For Sale'
  )
);
?>

**Comment by nathancarnes** [comment]
@JulianTosh I apologize for dropping the ball on this. If you still need help or are seeing an issue, please let me know.
