### ISSUE TITLE
Hyperlink from get_permalink() wrong

### ISSUE THREAD

**Issue by tommyready** [nathancarnes/MultiDomain#3]
I installed your plugin and the only problem I found was that in my navigation I used get_permalink() and it only returns the link to the primary domain.  Anyway around this?

**Comment by nathancarnes** [comment]
@tommyready -- which version of WordPress are you using? `get_permalink()` should work as expected.

**Comment by nathancarnes** [comment]
@tommyready going to close this out since I can't reproduce and I haven't heard back. If you're still using MultiDomain and seeing the issue, please feel free to reopen with more info. Thanks!
