### ISSUE TITLE
Blogdescription Syntax Error

### ISSUE THREAD

**Issue by Haxtro** [nathancarnes/MultiDomain#4]
Hi Nathan,

First, thanks for your awesome plugin! All the other options work great, but there is a bug while using 'blogdescription'. If you try to use it, the whole website will blank out! I've been looking in the code, everything seems okay. But I just can't get it work!

Can you help me out?

Thanks a lot!

Kind Regards,

Haxtro

**Comment by nathancarnes** [comment]
@Haxtro -- can you share your `config.php` with me? I tested out `blogdescription` under a few different versions of WordPress (including 3.6.1) and it's working fine for me. Thanks!

**Comment by Haxtro** [comment]
@nathancarnes Thanks for your response. I used your example config.php, as following:

<?php
  $domains = array(
    array(
      'domain' => 'mountshop.nl',
      'siteurl' => 'http://mountshop.nl',
      'home' => 'http://mountshop.nl'
    ),
    array(
      'domain' => 'mount-shop.nl',
      'siteurl' => 'http://mount-shop.nl',
      'home' => 'http://mount-shop.nl',
      'blogname' => 'Mount-Shop.nl'
    ),
    array(
      'domain' => 'mount-shop.com',
      'siteurl' => 'http://mount-shop.com',
      'home' => 'http://mount-shop.com',
      'blogname' => 'Mount-Shop.com'
      'blogdescription' => 'The site blahblah'
    )
  );
?>

When I tried it ( by WP editor ), the whole site blanked out. By Dreamweaver I could remove it again. But also Dreamweaver told me there was a syntax error!

Thanks again!

**Comment by nathancarnes** [comment]
@Haxtro -- you're missing a comma after your `blogname` line which is causing the syntax error. 

Try this version: https://gist.github.com/nathancarnes/be1e93fcc845f75a7274

**Comment by Haxtro** [comment]
Awesome, thanks! Sorry for inconvenience!

**Comment by nathancarnes** [comment]
No problem at all.
